org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.12.2
forge_version=14.23.5.2846
mapping_version=snapshot_20171003

mod_id=gdgquickjoin
mod_name=GDG Minecraft Quick Join
mod_license=All Rights Reserved
mod_version=0.2.1
mod_group_id=com.goldendaysgaming.minecraft
mod_authors=Golden Days Gaming
mod_description=Golden Days Gaming title-screen server status and quick-join UI for Stoneblock 2.
